Library_System_Project_Core/Controllers/LibraryManagement/BooksTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library_System_Project_Core.Data;
using Library_System_Project_Core.Models;

namespace Library_System_Project_Core.Controllers.LibraryManagement
{
    public class BooksTypesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public BooksTypesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: BooksTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.BooksType.ToListAsync());
        }

        // GET: BooksTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booksType = await _context.BooksType
                .FirstOrDefaultAsync(m => m.BooksTypeID == id);
            if (booksType == null)
            {
                return NotFound();
            }

            return View(booksType);
        }

        // GET: BooksTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BooksTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BooksTypeID,Name")] BooksType booksType)
        {
            if (ModelState.IsValid)
            {
                _context.Add(booksType);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(booksType);
        }

        // GET: BooksTypes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booksType = await _context.BooksType.FindAsync(id);
            if (booksType == null)
            {
                return NotFound();
            }
            return View(booksType);
        }

        // POST: BooksTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BooksTypeID,Name")] BooksType booksType)
        {
            if (id != booksType.BooksTypeID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booksType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BooksTypeExists(booksType.BooksTypeID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(booksType);
        }

        // GET: BooksTypes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booksType = await _context.BooksType
                .FirstOrDefaultAsync(m => m.BooksTypeID == id);
            if (booksType == null)
            {
                return NotFound();
            }

            return View(booksType);
        }

        // POST: BooksTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var booksType = await _context.BooksType.FindAsync(id);
            _context.BooksType.Remove(booksType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BooksTypeExists(int id)
        {
            return _context.BooksType.Any(e => e.BooksTypeID == id);
        }
    }
}

Library_System_Project_Core/Controllers/LibraryManagement/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Library_System_Project_Core.Data;
using Library_System_Project_Core.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Library_System_Project_Core.Controllers.LibraryManagement
{
    public class DetailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        //IHostingEnvironment _env;
        public DetailsController(ApplicationDbContext context) //IHostingEnvironment env
        {
            _context = context;
            //_env = env;
        }

        public ActionResult Index(string searchString, int? FacultyID, int? DepartmentID)
        {
            var singleSelectList = new SelectedDetailsModel();

            singleSelectList.Faculty = _context.Faculty.ToList();


            if (FacultyID == null)
            {
                byte[] kkk = HttpContext.Session.Get("FacultyID");

                if (kkk != null)
                {
                    string someString = Encoding.ASCII.GetString(kkk);
                    FacultyID = Convert.ToInt32(someString);
                }
            }

            if (FacultyID != null)
            {

                HttpContext.Session.SetString("FacultyID", FacultyID.ToString());
                singleSelectList.Department = _context.Department.Where(w => w.FacultyID == FacultyID.Value).ToList();


            }

            if (DepartmentID != null)
            {

                singleSelectList.Book = _context.Book.Include(i => i.BookTypes).Include(a => a.Author).Include(p => p.Publisher).Where(w => w.DepartmentID == DepartmentID.Value).ToList();

            }

            return View(singleSelectList);
            
        }
    }
}

Library_System_Project_Core/Controllers/LibraryManagement/FacultiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library_System_Project_Core.Data;
using Library_System_Project_Core.Models;
using Newtonsoft.Json;

namespace Library_System_Project_Core.Controllers.LibraryManagement
{
    public class FacultiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FacultiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Faculties
        public async Task<IActionResult> Index()
        {
            return View(await _context.Faculty.ToListAsync());
        }

        public IActionResult MultipleDataInsert()
        {
            return View();
        }

        [HttpPost]
        public JsonResult MultipleDataInsert(string facultyJson)
        {
            var js = new JsonSerializer();

            Faculty[] faculty = (Faculty[])Newtonsoft.Json.JsonConvert.DeserializeObject(facultyJson, typeof(Faculty[]));

            try
            {

                using (var dbContextTransaction = _context.Database.BeginTransaction())
                {
                    try
                    {
                        foreach (var v in faculty)
                        {
                            v.FacultyID = 0;
                            _context.Faculty.Add(v);
                            _context.SaveChanges();
                        }
                        dbContextTransaction.Commit();
                        return Json("Data are inserted in Faculty Table");

                    }
                    catch (Exception ex)
                    {
                        string ksks = ex.Message;
                        dbContextTransaction.Rollback();
                        return Json("There is a Probem arise");
                    }


                }
            }
            catch (Exception ex)
            {
                string ksks = ex.Message;
            }

            return Json("There is a Probem arise");

        }




        // GET: Faculties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculty
                .FirstOrDefaultAsync(m => m.FacultyID == id);
            if (faculty == null)
            {
                return NotFound();
            }

            return View(faculty);
        }

        // GET: Faculties/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Faculties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FacultyID,Name,Description")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _context.Add(faculty);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(faculty);
        }

        // GET: Faculties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculty.FindAsync(id);
            if (faculty == null)
            {
                return NotFound();
            }
            return View(faculty);
        }

        // POST: Faculties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FacultyID,Name,Description")] Faculty faculty)
        {
            if (id != faculty.FacultyID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(faculty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FacultyExists(faculty.FacultyID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(faculty);
        }

        // GET: Faculties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculty
                .FirstOrDefaultAsync(m => m.FacultyID == id);
            if (faculty == null)
            {
                return NotFound();
            }

            return View(faculty);
        }

        // POST: Faculties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var faculty = await _context.Faculty.FindAsync(id);
            _context.Faculty.Remove(faculty);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FacultyExists(int id)
        {
            return _context.Faculty.Any(e => e.FacultyID == id);
        }
    }
}

Library_System_Project_Core/Controllers/LibraryManagement/PublishersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library_System_Project_Core.Data;
using Library_System_Project_Core.Models;

namespace Library_System_Project_Core.Controllers.LibraryManagement
{
    public class PublishersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PublishersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Publishers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Publisher.ToListAsync());
        }

        // GET: Publishers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publisher
                .FirstOrDefaultAsync(m => m.PublisherID == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // GET: Publishers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Publishers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PublisherID,Name,Establish_Date,Address")] Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                _context.Add(publisher);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Publishers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publisher.FindAsync(id);
            if (publisher == null)
            {
                return NotFound();
            }
            return View(publisher);
        }

        // POST: Publishers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PublisherID,Name,Establish_Date,Address")] Publisher publisher)
        {
            if (id != publisher.PublisherID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(publisher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PublisherExists(publisher.PublisherID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(publisher);
        }

        // GET: Publishers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var publisher = await _context.Publisher
                .FirstOrDefaultAsync(m => m.PublisherID == id);
            if (publisher == null)
            {
                return NotFound();
            }

            return View(publisher);
        }

        // POST: Publishers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var publisher = await _context.Publisher.FindAsync(id);
            _context.Publisher.Remove(publisher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PublisherExists(int id)
        {
            return _context.Publisher.Any(e => e.PublisherID == id);
        }
    }
}

Library_System_Project_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang-"en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>@ViewData["Title"] - Library_System_Project_Core</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="~/lib/font-awesome/css/fontawesome.css" rel="stylesheet" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

    <style>
        body {
            background-color: #3b92eac2;
            
            font-family: 'Oxygen', sans-serif;
        }
        .navbar {
            background-image: url('../images/home/SOV.jpg');
        }

        .btn {
            background-color: slategray;
            background-color: #6c757d;
            border: none;
            color: white;
            font-size: 20px;
            cursor: pointer;
            height: 40px;
            text-align: center;
        }

        .dropbtn {
            font-size: 20px;
            border: none;
            outline: none;
            color: white;
            padding: 10px 16px;
            background-color: inherit;
            font-family: inherit;
            margin: 0;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #343a40eb;
            min-width: 10px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                color: white;
                padding: 5px 16px;
                text-decoration: none;
                display: block;
            }

                .dropdown-content a:hover {
                    background-color: #70b0ef;
                }

        /*.dropdown:hover .dropbtn {
            background-color: #a4c2d0c2;
        }*/

        .dropdown:hover .dropdown-content {
            display: block;
        }
    </style>


</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-secondary border-bottom fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a class="navbar-brand" href="/Home/Index"><img src="~/images/Home/SRlogo.jpg" alt="Company logo" width="50" height="40" class="rounded-circle" /> SR Library</a>

            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav nav-item">

                    @if (User.Identity.IsAuthenticated)
                    {


                        <li class="dropdown">
                            <button class="dropbtn"><i class="fa fa-university" style="font-size:25px;color: white"></i></button>
                            <div class="dropdown-content">
                                <a class="dropdown-item" href="@Url.Action("Index", "Faculties")">Faculty List</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Departments")">Departments List</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Authors")">Author List</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Publishers")">Publisher List</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Students")">Student LIst</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Teachers")">Teacher List</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Staffs")">Staff List</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "BooksTypes")">Books Types</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Books")">Book List</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "IssueingBookDetails")">Issue Book</a>

                            </div>
                        </li>

                        <li class="dropdown">
                            <button class="dropbtn"><i class="fa fa-bars" style="font-size: 30px; color: white"></i></button>
                            <div class="dropdown-content">
                                <a class="dropdown-item" href="@Url.Action("Index", "Authors")">Author List</a>
                                <a class="dropdown-item" href="@Url.Action("MultipleDataInsert", "Faculties")">Multiple Data Insert</a>
                                <a class="dropdown-item" href="@Url.Action("Index", "Details")">Details List</a>

                            </div>
                        </li>
                    }
                </ul>

            </div>
            <partial name="_Partiallogin" />
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <br /><br />
        <hr />
        <footer>

            <div class="row">

                <div class="col-md-6">
                    <h6 class="heading"><b>Developer Information</b></h6>
                    Name : Sharmin Akter<br />
                    Trainee ID : 1252366<br />
                    Batch : ESAD-CS/CGNT-M/41/01<br />
                    <i class="fa fa-map-marker" style="font-size: 25px; color: white"></i> Narayanganj, Dhaka <br />
                    <i class="fa fa-phone" style="font-size:25px;color:white"></i> +01688-656198<br />
                    <i class="fa fa-envelope-o" style="font-size:22px;color:white"></i> sharminakteridbr41@gmail.com
                </div>

                <div class="col-md-6">
                    <h6 class="heading"><b>Social Media Link</b></h6>
                    <a href="https://www.facebook.com/sharmin.rumpa.7" class="fa fa-facebook" style="font-size:30px; color:white"></a>
                    <a href="#" class="fa fa-twitter" style="font-size:30px; color:white"></a>
                    <a href="#" class="fa fa-google" style="font-size:30px; color:white"></a>
                    <a href="#" class="fa fa-linkedin" style="font-size:30px; color:white"></a>
                    <a href="#" class="fa fa-youtube" style="font-size:30px; color:white"></a>
                    <a href="#" class="fa fa-instagram" style="font-size:30px; color:white"></a>
                    <br /><br /><br />
                    <p><b>Information About Project</b><a class="nav-item">@Html.ActionLink("Project Link", "AboutProject", "Home", routeValues: null, htmlAttributes: new { id = "registerLink", @class = "nav-link" })</a></p>

                </div>

            </div>

        </footer>
        <hr />
        <div class="wrapper row5">
            <div id="copyright" class="hoc clear">
                <p class="fl_left">Copyright &copy; 2020-LibrarySystemManagement Project (On ASP.NET Core) - All Rights Reserved - <a href="#">Sharmin Akter</a></p>
            </div>
        </div>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Library_System_Project_Core/Views/Shared/_Partiallogin.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@


@if (User.Identity.IsAuthenticated)
{
    <li class="dropdown">
        <button class="dropbtn"><i class='fas fa-users' style='font-size:28px'></i></button>
        <div class="dropdown-content">
            <a class="dropdown-item" href="@Url.Action("RollCreate", "Account")">Role Create</a>
            <a class="dropdown-item" href="@Url.Action("UserList", "Account")">User List</a>
            <a class="dropdown-item" href="@Url.Action("RollList", "Account")">Roll List</a>
            <a class="dropdown-item" href="@Url.Action("RollMappingToUserList", "Account")">Role Provide To User</a>
            <a class="dropdown-item" href="@Url.Action("RoleAssignWithUser", "Account")">User List With Role</a>
            <a class="dropdown-item" href="@Url.Action("Index", "MenuHelperModels")">Create_Controler_Action</a>
            <a class="dropdown-item" href="@Url.Action("Index", "MenuModels")">Menu With Roll</a>
            <a class="dropdown-item" href="@Url.Action("View_RollPermission", "MenuModelManages")">Role Permission</a>
        </div>
    </li>
    <a><i class='fas fa-user-check' style='font-size:15px;color:white'></i>@User.Identity.Name!</a>
    <li class="dropdown">
        <button class="dropbtn"><i class="fa fa-info-circle" style="font-size:30px;color: white"></i></button>
        <div class="dropdown-content">
            <a class="dropdown-item" href="@Url.Action("About", "Home")">About Us</a>
            <a class="dropdown-item" href="@Url.Action("Vision", "Home")">Vision</a>
            <a class="dropdown-item" href="@Url.Action("Contact", "Home")">Contact</a>
            <a class="dropdown-item" href="@Url.Action("AboutProject", "Home")">About Project</a>

        </div>
    </li>
    <li class="dropdown">
        <button class="dropbtn"><i class='fas fa-user-lock' style='font-size:25px;color:white'></i></button>
        <div class="dropdown-content">
            <a class="dropdown-item" href="@Url.Action("Register", "Account")"><i class='fas fa-user-plus' style='font-size:25px;color:white'></i>  Sing Up</a>
            <a class="dropdown-item" href="@Url.Action("Login", "Account")"><i class='fa fa-sign-in' style='font-size:25px;color:white'></i>  Sing In</a>
            <a class="dropdown-item" href="@Url.Action("Logout", "Account")"><i class='fa fa-sign-out' style='font-size:25px;color:white'></i>  Sing Out</a>

        </div>
    </li>


}
else
{
    <div>

        <a href="@Url.Action("Index", "Home")"><i class='fas fa-home' style='font-size:25px;color:white'></i></a>
        <div class="dropdown">
            <button class="dropbtn"><i class="fa fa-info-circle" style="font-size:30px;color: white"></i></button>
            <div class="dropdown-content">
                <a class="dropdown-item" href="@Url.Action("About", "Home")">About Us</a>
                <a class="dropdown-item" href="@Url.Action("Vision", "Home")">Vision</a>
                <a class="dropdown-item" href="@Url.Action("Contact", "Home")">Contact</a>
                <a class="dropdown-item" href="@Url.Action("AboutProject", "Home")">About Project</a>

            </div>
        </div>
        <div class="dropdown">
            <button class="dropbtn"><i class='fas fa-user-lock' style='font-size:25px;color:white'></i></button>
            <div class="dropdown-content">
                <a class="dropdown-item" href="@Url.Action("Register", "Account")"><i class='fas fa-user-plus' style='font-size:20px;color:white'></i>  Sing Up</a>
                <a class="dropdown-item" href="@Url.Action("Login", "Account")"><i class='fa fa-sign-in' style='font-size:20px;color:white'></i>  Sing In</a>

            </div>
        </div>

    </div>

}