Library_System_Project_Core/Controllers/LibraryManagement/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library_System_Project_Core.Data;
using Library_System_Project_Core.Models;

namespace Library_System_Project_Core.Controllers.LibraryManagement
{
    public class DepartmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DepartmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Department.Include(d => d.Faculties);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .Include(d => d.Faculties)
                .FirstOrDefaultAsync(m => m.DepartmentID == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Departments/Create
        public IActionResult Create()
        {
            ViewData["FacultyID"] = new SelectList(_context.Faculty, "FacultyID", "Description");
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DepartmentID,Name,FacultyID")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FacultyID"] = new SelectList(_context.Faculty, "FacultyID", "Description", department.FacultyID);
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            ViewData["FacultyID"] = new SelectList(_context.Faculty, "FacultyID", "Description", department.FacultyID);
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DepartmentID,Name,FacultyID")] Department department)
        {
            if (id != department.DepartmentID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.DepartmentID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FacultyID"] = new SelectList(_context.Faculty, "FacultyID", "Description", department.FacultyID);
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .Include(d => d.Faculties)
                .FirstOrDefaultAsync(m => m.DepartmentID == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var department = await _context.Department.FindAsync(id);
            _context.Department.Remove(department);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
            return _context.Department.Any(e => e.DepartmentID == id);
        }
    }
}

Library_System_Project_Core/Controllers/LibraryManagement/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Library_System_Project_Core.Data;
using Library_System_Project_Core.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Library_System_Project_Core.Controllers.LibraryManagement
{
    public class DetailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        //IHostingEnvironment _env;
        public DetailsController(ApplicationDbContext context) //IHostingEnvironment env
        {
            _context = context;
            //_env = env;
        }

        public ActionResult Index(string searchString, int? FacultyID, int? DepartmentID)
        {
            var singleSelectList = new SelectedDetailsModel();

            singleSelectList.Faculty = _context.Faculty.ToList();


            if (FacultyID == null)
            {
                byte[] kkk = HttpContext.Session.Get("FacultyID");

                if (kkk != null)
                {
                    string someString = Encoding.ASCII.GetString(kkk);
                    FacultyID = Convert.ToInt32(someString);
                }
            }

            if (FacultyID != null)
            {

                HttpContext.Session.SetString("FacultyID", FacultyID.ToString());
                singleSelectList.Department = _context.Department.Where(w => w.FacultyID == FacultyID.Value).ToList();


            }

            if (DepartmentID != null)
            {

                singleSelectList.Book = _context.Book.Include(i => i.BookTypes).Include(a => a.Author).Include(p => p.Publisher).Where(w => w.DepartmentID == DepartmentID.Value).ToList();

            }

            return View(singleSelectList);
            
        }
    }
}

Library_System_Project_Core/Controllers/LibraryManagement/FacultiesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Library_System_Project_Core.Data;
using Library_System_Project_Core.Models;
using Newtonsoft.Json;

namespace Library_System_Project_Core.Controllers.LibraryManagement
{
    public class FacultiesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FacultiesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Faculties
        public async Task<IActionResult> Index()
        {
            return View(await _context.Faculty.ToListAsync());
        }

        public IActionResult MultipleDataInsert()
        {
            return View();
        }

        [HttpPost]
        public JsonResult MultipleDataInsert(string facultyJson)
        {
            var js = new JsonSerializer();

            Faculty[] faculty = (Faculty[])Newtonsoft.Json.JsonConvert.DeserializeObject(facultyJson, typeof(Faculty[]));

            try
            {

                using (var dbContextTransaction = _context.Database.BeginTransaction())
                {
                    try
                    {
                        foreach (var v in faculty)
                        {
                            v.FacultyID = 0;
                            _context.Faculty.Add(v);
                            _context.SaveChanges();
                        }
                        dbContextTransaction.Commit();
                        return Json("Data are inserted in Faculty Table");

                    }
                    catch (Exception ex)
                    {
                        string ksks = ex.Message;
                        dbContextTransaction.Rollback();
                        return Json("There is a Probem arise");
                    }


                }
            }
            catch (Exception ex)
            {
                string ksks = ex.Message;
            }

            return Json("There is a Probem arise");

        }




        // GET: Faculties/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculty
                .FirstOrDefaultAsync(m => m.FacultyID == id);
            if (faculty == null)
            {
                return NotFound();
            }

            return View(faculty);
        }

        // GET: Faculties/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Faculties/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FacultyID,Name,Description")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _context.Add(faculty);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(faculty);
        }

        // GET: Faculties/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculty.FindAsync(id);
            if (faculty == null)
            {
                return NotFound();
            }
            return View(faculty);
        }

        // POST: Faculties/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FacultyID,Name,Description")] Faculty faculty)
        {
            if (id != faculty.FacultyID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(faculty);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FacultyExists(faculty.FacultyID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(faculty);
        }

        // GET: Faculties/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faculty = await _context.Faculty
                .FirstOrDefaultAsync(m => m.FacultyID == id);
            if (faculty == null)
            {
                return NotFound();
            }

            return View(faculty);
        }

        // POST: Faculties/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var faculty = await _context.Faculty.FindAsync(id);
            _context.Faculty.Remove(faculty);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FacultyExists(int id)
        {
            return _context.Faculty.Any(e => e.FacultyID == id);
        }
    }
}

Library_System_Project_Core/Views/Details/BookPartialView.cshtml
@model Library_System_Project_Core.Data.SelectedDetailsModel

<br />
<h2 class="text-center">Department Wise Book List</h2>
<table class="table table-hover table-dark">
    <thead>
        <tr>
            <th>
                Department Name
            </th>
            <th>
                BooksType
            </th>
            <th>
                Book Title
            </th>
            <th>
                Author Name
            </th>
            <th>
                ISBN
            </th>
            <th>
                NoOfPage
            </th>
            <th>
                ImageUrl
            </th>

            <th>
                Publisher Name
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model.Book)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Departments.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BookTypes.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ISBN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoOfPage)
            </td>
            <td>
                <img src="@Url.Content(item.ImageUrl)" width="120" height="120" class="rounded" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Publisher.Name)
            </td>
            <td>
                @*<a href="@Url.Action("Index", "Details", new { BookID = item.BookID })" class="btn btn-secondary btn-sm mr-1">Select</a>*@
                <a href="@Url.Action("Edit", "Books", new { id = item.BookID })" class="btn btn-secondary btn-sm mr-1"><i class="fa fa-edit"></i></a>
                <a href="@Url.Action("Details", "Books", new { id = item.BookID })" class="btn btn-secondary btn-sm mr-1"><i class=" fa fa-bars"></i></a>
                <a href="@Url.Action("Delete", "Books", new { id = item.BookID })" class="btn btn-secondary btn-sm mr-1"><i class=" fa fa-trash"></i></a>
            </td>
        </tr>
    }


</table>

Library_System_Project_Core/Views/Details/DepartmentPartialView.cshtml
@model Library_System_Project_Core.Data.SelectedDetailsModel

<br />
<h2 class="text-center">Faculty Wise Department List</h2>
<table class="table table-hover table-dark">
    <thead >
        <tr>
            <th>
                Department Name
            </th>
            <th></th>
        </tr>
    </thead>

    @foreach (var item in Model.Department)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>

            <td>

                <a href="@Url.Action("Index", "Details", new { DepartmentID = item.DepartmentID })" class="btn btn-secondary btn-sm mr-1">Select</a>
                <a href="@Url.Action("Edit", "Departments", new { id = item.DepartmentID })" class="btn btn-secondary btn-sm mr-1"><i class="fa fa-edit"></i></a> 
                <a href="@Url.Action("Details", "Departments", new { id = item.DepartmentID })" class="btn btn-secondary btn-sm mr-1"><i class=" fa fa-bars"></i></a>
                <a href="@Url.Action("Delete", "Departments", new { id = item.DepartmentID })" class="btn btn-secondary btn-sm mr-1"><i class=" fa fa-trash"></i></a>


                @*@Html.ActionLink("Select", "Index", new { DepartmentID = item.DepartmentID }) |
                    @Html.ActionLink("Edit", "Edit", "Departments", new { id = item.DepartmentID }, null) |
                    @Html.ActionLink("Details", "Details", "Departments", new { id = item.DepartmentID }, null) |
                    @Html.ActionLink("Delete", "Delete", "Departments", new { id = item.DepartmentID }, null)*@
            </td>
        </tr>
    }




</table>

Library_System_Project_Core/Views/Details/Index.cshtml
@model Library_System_Project_Core.Data.SelectedDetailsModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />



@if (Model != null)
{
<div class="container">


    @if (Model.Book != null)
    {
        <partial name="BookPartialView" />
        
    }

    <br />
    @if (Model.Department != null)
    {
        <partial name="DepartmentPartialView" />
       
    }

    <br />
    <h2 class="text-center">Faculty List</h2>
    <br />
    <table class="table table-hover table-dark">
        <thead>
            <tr>
                <th>
                    Faculty Name
                </th>
                <th></th>
            </tr>
        </thead>
        @if (Model.Faculty != null)
        {
            foreach (var item in Model.Faculty)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <a href="@Url.Action("Index", "Details", new { FacultyID = item.FacultyID })" class="btn btn-secondary btn-sm mr-1">Select</a>
                        <a href="@Url.Action("Edit", "Faculties", new { id = item.FacultyID })" class="btn btn-secondary btn-sm mr-1"><i class="fa fa-edit"></i></a>
                        <a href="@Url.Action("Details", "Faculties", new { id = item.FacultyID })" class="btn btn-secondary btn-sm mr-1"><i class=" fa fa-bars"></i></a>
                        <a href="@Url.Action("Delete", "Faculties", new { id = item.FacultyID })" class="btn btn-secondary btn-sm mr-1"><i class=" fa fa-trash"></i></a>
                    </td>
                </tr>
            }

        }


    </table>



</div>
}